In [99]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
penguin_size = pd.read_csv("penguins_size.csv")

In [122]:
penguin_size.tail(10)

species  island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
334  Gentoo  Biscoe              46.2             14.1              217.0   
335  Gentoo  Biscoe              55.1             16.0              230.0   
336  Gentoo  Biscoe              44.5             15.7              217.0   
337  Gentoo  Biscoe              48.8             16.2              222.0   
338  Gentoo  Biscoe              47.2             13.7              214.0   
339  Gentoo  Biscoe               NaN              NaN                NaN   
340  Gentoo  Biscoe              46.8             14.3              215.0   
341  Gentoo  Biscoe              50.4             15.7              222.0   
342  Gentoo  Biscoe              45.2             14.8              212.0   
343  Gentoo  Biscoe              49.9             16.1              213.0   

     body_mass_g     sex  
334       4375.0  FEMALE  
335       5850.0    MALE  
336       4875.0       .  
337       6000.0    MALE  
338       4925.0  FEMALE  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE

In [123]:
penguin_size.describe()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         200.915205  4201.754386
std            5.459584         1.974793          14.061714   801.954536
min           32.100000        13.100000         172.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.000000  4750.000000
max           59.600000        21.500000         231.000000  6300.000000

In [124]:
#checking the missing value
penguin_size.isna().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [125]:
#let's deal with missing value for numerical data
mean=penguin_size.mean()

penguin_size= penguin_size.replace(np.nan, mean) #replaceing missing value for numerical data with mean

In [126]:
#let's check what kind of sex is most frequent
penguin_size.sex.value_counts()

MALE      168
FEMALE    165
.           1
Name: sex, dtype: int64

In [127]:
#let's fill the missing value of "sex" table with the most frequent value

# fill the null values in sex by the most frequent value: "male"
penguin_size.sex.fillna('MALE', inplace=True)

In [128]:
#let's check the missing value of our dataset once again

penguin_size.isna().sum()

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [129]:
penguin_size.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen          39.10000         18.70000         181.000000   
1  Adelie  Torgersen          39.50000         17.40000         186.000000   
2  Adelie  Torgersen          40.30000         18.00000         195.000000   
3  Adelie  Torgersen          43.92193         17.15117         200.915205   
4  Adelie  Torgersen          36.70000         19.30000         193.000000   

   body_mass_g     sex  
0  3750.000000    MALE  
1  3800.000000  FEMALE  
2  3250.000000  FEMALE  
3  4201.754386    MALE  
4  3450.000000  FEMALE

In [130]:
#let's convert the categorical data to be numerical data, so we can apply machine learning algorithm to dataset
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [131]:
penguin_size['species']=label_encoder.fit_transform(penguin_size['species'])
penguin_size['island']=label_encoder.fit_transform(penguin_size['island'])
penguin_size['sex']=label_encoder.fit_transform(penguin_size['sex'])

In [132]:
penguin_size

species  island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0          0       2          39.10000         18.70000         181.000000   
1          0       2          39.50000         17.40000         186.000000   
2          0       2          40.30000         18.00000         195.000000   
3          0       2          43.92193         17.15117         200.915205   
4          0       2          36.70000         19.30000         193.000000   
..       ...     ...               ...              ...                ...   
339        2       0          43.92193         17.15117         200.915205   
340        2       0          46.80000         14.30000         215.000000   
341        2       0          50.40000         15.70000         222.000000   
342        2       0          45.20000         14.80000         212.000000   
343        2       0          49.90000         16.10000         213.000000   

     body_mass_g  sex  
0    3750.000000    2  
1    3800.000000    1  
2    3250.000000    1  
3    4201.754386    2  
4    3450.000000    1  
..           ...  ...  
339  4201.754386    2  
340  4850.000000    1  
341  5750.000000    2  
342  5200.000000    1  
343  5400.000000    2  

[344 rows x 7 columns]

# let's apply classification algorithms to define the type of penguin based on its size and what island they're living

I apply 5 classification algorithms to penguin size dataset

they are :
1. logistic regression
2. K Neighbors 
3. Random Forest classification
4. Support Vector Machine
5. Kernel SVM

I apply those five to evaluate and compare which algorithm that give the highest accuracy

In [ ]:
x= penguin_size.iloc[:, [1,2,3,4,5]].values
y= penguin_size.iloc[:, [0]].values

In [134]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [135]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# 1. logistic regression

In [136]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=0)

In [137]:
y_pred = classifier.predict(x_test)

In [138]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[42  0  0]
 [ 1 13  0]
 [ 0  0 30]]


0.9883720930232558

# 2. K Nearest Neigbors

In [140]:
from sklearn.neighbors import KNeighborsClassifier
model_classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_classifier.fit(x_train, y_train)

<ipython-input-140-fa704fe3390c>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  model_classifier.fit(x_train, y_train)


KNeighborsClassifier()

In [141]:
y_pred_2 = model_classifier.predict(x_test)

In [142]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_2 = confusion_matrix(y_test, y_pred_2)
print(cm_2)
accuracy_score(y_test, y_pred_2)

[[40  2  0]
 [ 0 14  0]
 [ 0  0 30]]


0.9767441860465116

# 3. Random Forest classification

In [143]:
from sklearn.ensemble import RandomForestClassifier
classifier_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_forest.fit(x_train, y_train)

<ipython-input-143-eea28653fa6d>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier_forest.fit(x_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [144]:
y_predict_3= classifier_forest.predict(x_test)

In [151]:
y_predict_3

array([0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0,
       1, 0, 2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 2,
       2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2])

In [146]:
cm_3 = confusion_matrix(y_test, y_predict_3)
print(cm_3)
accuracy_score(y_test, y_predict_3)

[[42  0  0]
 [ 1 13  0]
 [ 0  0 30]]


0.9883720930232558

# 4. Support Vector Machine

In [147]:
from sklearn.svm import SVC
classifier_svc = SVC(kernel = 'linear', random_state = 0)
classifier_svc.fit(x_train, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(kernel='linear', random_state=0)

In [148]:
y_pred_4 = classifier_svc.predict(x_test)

In [150]:
y_pred_4

array([0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0,
       1, 0, 2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 2,
       2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2])

In [149]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_4 = confusion_matrix(y_test, y_pred_4)
print(cm_4)
accuracy_score(y_test, y_pred_4)

[[42  0  0]
 [ 1 13  0]
 [ 0  0 30]]


0.9883720930232558

# 5. kernel svm

In [152]:
from sklearn.svm import SVC
classifier_kernel = SVC(kernel = 'rbf', random_state = 0)
classifier_kernel.fit(x_train, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(random_state=0)

In [153]:
y_pred_5 = classifier_kernel.predict(x_test)

In [154]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_5 = confusion_matrix(y_test, y_pred_5)
print(cm_5)
accuracy_score(y_test, y_pred_5)

[[42  0  0]
 [ 0 14  0]
 [ 0  0 30]]


1.0

# Findings

from the 5 algorithms applied, kernel SVM gives the highest accuracy. Meanwhile KNN gives the lowest accuracy, and the rest applied algorithm give the same accuracy. So for this kind of dataset, it's better to apply kernel svm if you want to predict the species of penguin based on their size and location (island) they live in. 

but i don't con